export default {
  LOAD_MOVIES_REQUEST: "movies/LOAD_MOVIES_REQUEST",
  LOAD_MOVIES_SUCCESS: "movies/LOAD_MOVIES_SUCCESS",
  LOAD_MOVIES_FAILURE: "movies/LOAD_MOVIES_FAILURE",

  LOAD_DETAILS_REQUEST: "movies/LOAD_DETAILS_REQUEST",
  LOAD_DETAILS_SUCCESS: "movies/LOAD_DETAILS_SUCCESS",
  LOAD_DETAILS_FAILURE: "movies/LOAD_DETAILS_FAILURE"
};
