export default {
  LOAD_BOOKS_REQUEST: "books/LOAD_BOOKS_REQUEST",
  LOAD_BOOKS_SUCCESS: "books/LOAD_BOOKS_SUCCESS",
  LOAD_BOOKS_FAILURE: "books/LOAD_BOOKS_FAILURE",

  LOAD_DETAILS_REQUEST: "books/LOAD_DETAILS_REQUEST",
  LOAD_DETAILS_SUCCESS: "books/LOAD_DETAILS_SUCCESS",
  LOAD_DETAILS_FAILURE: "books/LOAD_DETAILS_FAILURE"
};
